### ISSUE TITLE
Would it be nice to add some complete public manuals?

### ISSUE THREAD

**Issue by MarcelXia** [mehdihadeli/awesome-go-education#10]
(I have those links if you need them)

And another idea is to have this linked fro within Awesome Go

**Comment by mehdihadeli** [comment]
Hey,
What are you mean about public manuals?
Could you send me a sample?

**Comment by MarcelXia** [comment]
Idk if you covered the following (some are on a specific topic, others are more complete)
https://www.karanpratapsingh.com/courses/go
https://github.com/softchris/golang-book
https://github.com/dariubs/GoBooks
https://go.dev/doc/tutorial/generics
https://github.com/callicoder/golang-tutorials
https://miek.nl/go/
https://go101.org/article/101.html
http://tmrts.com/go-patterns/#messaging-patterns
https://gobyexample.com/
https://www.reddit.com/r/golang/comments/9q0s37/go_programming_language_tutorials/
https://www.golangprograms.com/
https://golangbot.com/learn-golang-series/

**Comment by marcelloh** [comment]
Nice :-)

**Comment by mehdihadeli** [comment]
@marcelloh Done
